### ISSUE TITLE
Startup crash on 1.19.2 dedicated server

### ISSUE THREAD

**Issue by zack-emmert** [Mithion/Mystic-Alchemy#10] opened 2023-09-28 16:48 UTC
Attempting to start up a dedicated server with MC 1.19.2, Forge 43.3.0, and Mystic Alchemy 0.2.0 results in the included crash log. No other mods were loaded, and an identically set up client started without issue.

[latest.log](https://github.com/Mithion/Mystic-Alchemy/files/12751999/latest.log)

**Comment by animatedosprey** [comment] 2023-09-29 14:14
getting this too.  Bing ai says its an issue caused by the server trying to load client-side tags or something ;(  Awaiting a fix

**Comment by Notoromus** [comment] 2024-04-03 23:48
Same bug, mod is calling for the localplayer class which stops it from loading on servers

**Comment by Mithion** [comment] 2024-04-17 23:40
This is resolved in 0.3.0

**Closed as completed by Mithion** 2024-04-17 23:40 UTC
Labels: bug

**Comment by jajoe98** [comment] 2024-06-08 23:01
is there a 1.19.2 release for the 0.3.0 version of the mod? I cant seem to find one and not sure if I'm just missing it. The only one I've managed to find was for 1.20.1 but the original post here is about 1.19.2
